/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-11-16 02:38:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.fundadmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.15.RELEASE.jar", Long.valueOf(1665053849411L));
    _jspx_dependants.put("jar:file:/C:/Users/unionmk/FundManagerSeirenHoldings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.10.RELEASE.jar", Long.valueOf(1665053875299L));
    _jspx_dependants.put("jar:file:/C:/Users/unionmk/FundManagerSeirenHoldings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/spring-security-taglibs-5.2.10.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1618216572000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665053931769L));
    _jspx_dependants.put("jar:file:/C:/Users/unionmk/FundManagerSeirenHoldings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/C:/Users/unionmk/FundManagerSeirenHoldings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/C:/Users/unionmk/FundManagerSeirenHoldings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/spring-webmvc-5.2.15.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1620770806000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Fund Manager System | Log in</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- icheck bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/css/adminlte.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/crm/css/sh.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition login-page\">\r\n");
      out.write("<div class=\"login-box\">\r\n");
      out.write("  <div class=\"login-logo\"> <img  class=\" login-box-msg\" style=\"width: 176px;\r\n");
      out.write("    border-radius: 33px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/img/AdminLTELogo.jpg\">\r\n");
      out.write("    <br>\r\n");
      out.write("    <b><span style=\"font-size:18px\">Seiren Holdings</span></b>\r\n");
      out.write("    <br><a href=\"/portal/fundadmin/login\">Fund Admin System </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.login-logo -->\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    <div class=\"card-body login-card-body\">\r\n");
      out.write("      <p class=\"login-box-msg\">Sign in to start your session</p>\r\n");
      out.write("\r\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/crm/loginConfirm\" method=\"get\" name=\"loginFrm\" id=\"loginFrm\">\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"text\" id=\"login\" name=\"login\" class=\"form-control\" placeholder=\"Login\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Password\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-8\">\r\n");
      out.write("            <div class=\"icheck-primary\">\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("          <div class=\"col-4\">\r\n");
      out.write("            <button  id=\"signinbtn\" type=\"button\" onClick=\"javascript:check();\" class=\"btn btn-primary btn-block\">Sign In</button>\r\n");
      out.write("            <!-- <a href=\"javascript:check();\">Sign In</a> -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("     <!--   <div class=\"social-auth-links text-center mb-3\">\r\n");
      out.write("        <p>- OR -</p>\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-block btn-primary\">\r\n");
      out.write("          <i class=\"fab fa-facebook mr-2\"></i> Sign in using Facebook\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-block btn-danger\">\r\n");
      out.write("          <i class=\"fab fa-google-plus mr-2\"></i> Sign in using Google+\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>-->\r\n");
      out.write("      <!-- /.social-auth-links -->\r\n");
      out.write("\r\n");
      out.write("    <!--   <p class=\"mb-1\">\r\n");
      out.write("        <a href=\"forgot-password.html\">I forgot my password</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <p class=\"mb-0\">\r\n");
      out.write("        <a href=\"register.html\" class=\"text-center\">Register a new membership</a>\r\n");
      out.write("      </p>--> \r\n");
      out.write("        <p style=\"text-align:center\">\r\n");
      out.write("      <strong>Copyright &copy; 2023 <a href=\"#\"></a>.\r\n");
      out.write("	</strong> All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.login-card-body -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.login-box -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function check(){\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	if(document.loginFrm.login.value==\"\"){\r\n");
      out.write("		alert(\"Please enter your login.\")\r\n");
      out.write("		document.loginFrm.login.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.loginFrm.password.value==\"\"){\r\n");
      out.write("		alert(\"Please enter your master password.\")\r\n");
      out.write("		document.loginFrm.password.focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	document.getElementById(\"signinbtn\").innerHTML ='<i class=\"fa fa-spinner fa-spin\"></i>';\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fundadmin/loginConfirm',\r\n");
      out.write("		type : 'get',\r\n");
      out.write("		async: false,\r\n");
      out.write("		data : $(\"#loginFrm\").serialize(),\r\n");
      out.write("		success : function(data) {\r\n");
      out.write("			console.log(\"hi\");\r\n");
      out.write("			console.log(data.result);\r\n");
      out.write("			if (data.result == \"SUCCESS\") {\r\n");
      out.write("				self.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fundadmin/index\";\r\n");
      out.write("			} else {\r\n");
      out.write("				document.getElementById(\"signinbtn\").innerHTML ='Sign In';\r\n");
      out.write("				alert(data.result);\r\n");
      out.write("				return ;			\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		error : function(xhr, status) {\r\n");
      out.write("			document.getElementById(\"signinbtn\").innerHTML ='Sign In';\r\n");
      out.write("            alert(\"ERROR : \" +data.result + xhr + \" : \" + status);\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
